### ISSUE TITLE
Use of .decode() with Python 3

### ISSUE THREAD

**Issue by christian-oreilly** [mhe/pynrrd#27] opened 2017-08-04 14:04 UTC
Doing 

```
import nrrd
nrrd.read_header('atlas.nrrd')
```

in Python 3.4 I get 

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-5ee79514b6ef> in <module>()
      1 import nrrd
----> 2 nrrd.read_header('atlas.nrrd')

/gpfs/bbp.cscs.ch/project/proj55/oreilly/python_venv/venv-3.4/lib/python3.4/site-packages/nrrd.py in read_header(nrrdfile)
    336     it = iter(nrrdfile)
    337 
--> 338     headerSize += _validate_magic_line(next(it).decode('ascii'))
    339 
    340     header = { u'keyvaluepairs': {} }

AttributeError: 'str' object has no attribute 'decode'
```

which seems to me a like python2-to-python3 conversion issue...

**Comment by christian-oreilly** [comment] 2017-08-04 14:10
... I just tried it with Python 2.7. I get 

```
---------------------------------------------------------------------------
NrrdError                                 Traceback (most recent call last)
<ipython-input-3-dcc087f5fd48> in <module>()
      4 with open('atlas.nrrd', 'wb') as f:
      5     f.write(my_data.content)
----> 6 nrrd.read_header('atlas.nrrd')

/gpfs/bbp.cscs.ch/project/proj55/oreilly/python_venv/venv-2.7/lib/python2.7/site-packages/nrrd.pyc in read_header(nrrdfile)
    336     it = iter(nrrdfile)
    337 
--> 338     headerSize += _validate_magic_line(next(it).decode('ascii'))
    339 
    340     header = { u'keyvaluepairs': {} }

/gpfs/bbp.cscs.ch/project/proj55/oreilly/python_venv/venv-2.7/lib/python2.7/site-packages/nrrd.pyc in _validate_magic_line(line)
    309     """
    310     if not line.startswith('NRRD'):
--> 311         raise NrrdError('Missing magic "NRRD" word. Is this an NRRD file?')
    312     try:
    313         if int(line[4:]) > 5:

NrrdError: Missing magic "NRRD" word. Is this an NRRD file?
```

which seems odd... 

`cat atlas.nrrd | head`

gives

```
NRRD0005
# This NRRD file was generated by pynrrd
# on 2017-05-11 15:17:23(GMT).
# Complete NRRD file format specification at:
# http://teem.sourceforge.net/nrrd/format.html
type: uint16
dimension: 3
space: left-posterior-superior
sizes: 409 608 286
space directions: (39.9999991059303213,0,0) (0,39.9999991059303213,0) (0,0,-39.9999991059303213)
```

**Comment by mhe** [comment] 2017-08-09 19:41
Thanks for your report. Which version of pynrrd are you using? Do the files in the test directory work for you?

**Comment by anki-xyz** [comment] 2017-08-10 09:30
I was having the same issue.
I generated an NRRD file from ImageJ. By using the "closed" issue workaround with the most recent version of pynrrd I could at least read the file via `nrrd.read` command. The `nrrd.read_header` gives me the same error.

**Comment by christian-oreilly** [comment] 2017-08-11 08:21
I have pynrrd installed with
`pip install git+https://github.com/mhe/pynrrd.git --upgrade`
so it is the code as is in the master of the GitHub repo. As for the tests, the result is as follow 

```
..........
----------------------------------------------------------------------
Ran 10 tests in 0.030s

OK
```

Ran through Jupyter Notebooks, Python 3.4, Ubuntu 16.04

**Comment by addisonElliott** [comment] 2017-11-28 04:36
Are you still having issues? If not, you can probably close this issue

**Comment by christian-oreilly** [comment] 2017-12-04 17:38
Yes, still having the exact same errors after updating with the last github version of pynrrd.

**Comment by addisonElliott** [comment] 2017-12-04 17:59
Alright, it took me a second but I finally got it figured out what the issue is.

If you look at how `read_header` is used in the library, you are supposed to pass it a **file handle**, not a file name like you did. Look [here](https://github.com/mhe/pynrrd/blob/master/nrrd.py#L378)

The reason you are getting the odd error message is because there is not a check for whether the argument to `read_header` is valid. 

Here is the code you should use:
```
import nrrd
with open('atlas.nrrd', 'rb') as fh:
    nrrd.read_header(fh)
```

I definitely think there should be a check for the input argument to `read_header` and maybe some of the other functions. The other option is to modify `read_header` to open the filename if a string is given. 

Do you want to issue a pull request for this? If not, I'll submit one.

**Comment by anki-xyz** [comment] 2017-12-06 09:01
thanks @addisonElliott - if you could submit one it would be great.

**Comment by addisonElliott** [comment] 2017-12-07 17:13
What I did is fixed this issue so it returns:
```
nrrd.NrrdError: Missing magic "NRRD" word. Is this an NRRD file?
```

instead of the error you saw. It is more clear what the issue is when seeing this new message.

**Comment by mhe** [comment] 2017-12-25 10:32
Thank you @addisonElliott  for your contribution, it is now merged. I assume this issue can now be closed.

**Closed by mhe** 2017-12-25 10:32 UTC
